### PR TITLE
added functions newEndpoint, newEnvironment, assignEP2Env

### PR DESCRIPTION
**Pull request by piyush94**
Existing issues in function newEndpoint:
1. Endpoint credential is not getting set.
2. Endpoint types are not getting set.

Both didn't worked from swagger URL also.

Data used for testing:
```
def serverattrs = [
            "type": "Unix",
            "hostname": "abc.xyz.com",
            "protocol": "sftp",
            "basedir": "/tmp",
            "credname": "GLOBAL.linux",
            "autoping": "N",
            "comptype": "Application File",
            "sshport": "22"
];
```

### CODE REVIEW

**Comment by sbtaylor15** [comment]
@piyush94 you need to use the def updateEndpointAttrs(String url, String userid, String pw, String endpointname, Map Attrs) after you create the end point.  Passing the Attrs to the create end point wont work.  The same goes for environments.

updateEndpointAttrs and updateEnvironmentAttrs are already defined in the groovy script.

**Comment by piyush94** [comment]
@sbtaylor15 i used updateEndpointAttrs, but now all of them are getting set on Attributes tab instead of General tab.
image

**Comment by sbtaylor15** [comment]
@piyush94 we are going to change the backend to handle the endpoint and environment updates to be consistent with components and applications.

**Comment by sbtaylor15** [comment]
@piyush94 we updated the backend to handle the server attributes like components and applications. 

Remove the attributes from the end point and then put the latest image in place.  The groovy script should not need any additional changes.

**Comment by piyush94** [comment]
@sbtaylor15 thanks, all the attributes are getting updated now except "comptype". It works with single  value but not with CSV e.g. "comptype": "Docker_EP,Application File".

**Comment by sbtaylor15** [comment]
@piyush94 we updated the back to handle csv component types.

**Pull request merged**
